version: '3.8'

networks:
  sample:

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
      - "443:443"
    container_name: sample_nginx
    networks:
      - sample
    depends_on:
      - php
    
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes: 
      - ./:/var/www/html
    container_name: sample_php
    networks:
      - sample
    depends_on:
      - mysql

  mysql:
    image: mysql
    tty: true
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    container_name: sample_mysql
    networks:
      - sample